service: Moment
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-prune-versions
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  exclude:
    - node_modules/**

custom:
  prune:
    automatic: true
    number: 2

functions:
  GetMoment:
    handler: handler.GetMoment
    events:
      - httpApi:
          path: /GetMoment
          method: get