service: ts-endpoint
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  authentication:
    handler: handler.authentication
    events:
      - httpApi:
          path: /authentication
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
